backend:
  name: git-gateway
  branch: main
  repo: Oussama-kazzi/My_Portfolio


media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    extension: "json"
    format: "json"
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tech Stack", name: "tech", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Live Link", name: "liveLink", widget: "string", required: false }
      - { label: "GitHub Link", name: "githubLink", widget: "string", required: false }

  - name: "skills"
    label: "Skills"
    files:
      - label: "Skills List"
        name: "skills_list"
        file: "src/content/skills.json"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Category Name", name: "category", widget: "string" }
              - label: "Skills"
                name: "skills"
                widget: "list"
                fields:
                  - { label: "Skill Name", name: "name", widget: "string" }
                  - { label: "Icon Name (Lucide)", name: "icon", widget: "string" }

  - name: "profile"
    label: "Profile"
    files:
      - label: "About Me"
        name: "about"
        file: "src/content/profile.json"
        fields:
          - { label: "About Paragraph", name: "about_paragraph", widget: "text" }
